# RAND Research Area Mapping
# Maps local_data values to research areas based on RAND's organizational structure

RESEARCH_AREA_MAPPING = {
    # Arroyo Center (Army FFRDC)
    'Arroyo Center': 'Arroyo Center',
    'Arroyo Center.': 'Arroyo Center',
    'Arroyo center': 'Arroyo Center',
    'RAND Army Research Division': 'Arroyo Center',
    'RAND Army Research Division': 'Arroyo Center',
    'Army Research Division': 'Arroyo Center',
    'Army Research': 'Arroyo Center',
    'Army Research': 'Arroyo Center',
    
    # Project Air Force (Air Force FFRDC)
    'Project Air Force': 'Project Air Force',
    'Project Air Force.': 'Project Air Force',
    'Project AIR FORCE': 'Project Air Force',
    'RAND Project AIR FORCE': 'Project Air Force',
    'RAND Project Air Force': 'Project Air Force',
    'RAND Project Air Force': 'Project Air Force',
    'RAND Project AIR FORCE Division': 'Project Air Force',
    'Aero-Astronautics': 'Project Air Force',
    'Aero-astronautics': 'Project Air Force',
    'Aero Astronautics': 'Project Air Force',
    'Aircraft': 'Project Air Force',
    'Missiles': 'Project Air Force',
    'Missiles.': 'Project Air Force',
    'Airborne Vehicles': 'Project Air Force',
    'Bomber Group': 'Project Air Force',
    'Propulsion Group': 'Project Air Force',
    
    # National Defense Research Institute (Navy/Marine FFRDC)
    'National Defense Research Institute': 'National Defense Research Institute',
    'National Defense Research Division': 'National Defense Research Institute',
    'Navy and Marine Forces Center': 'National Defense Research Institute',
    
    # Homeland Security Research Division (DHS FFRDC)
    'Homeland Security Research Division': 'Homeland Security Research Division',
    'RAND Homeland Security Research Division': 'Homeland Security Research Division',
    'Homeland Security Operational Analysis Center': 'Homeland Security Research Division',
    'Homeland Security Research Division': 'Homeland Security Research Division',
    
    # RAND Health
    'RAND Health': 'RAND Health',
    'RAND Health Care': 'RAND Health',
    'RAND Health Care': 'RAND Health',
    'Health Care': 'RAND Health',
    'Rand Health': 'RAND Health',
    'Health Sciences': 'RAND Health',
    'Health Promotion and Disease Prevention': 'RAND Health',
    'Population Health': 'RAND Health',
    'Global Health': 'RAND Health',
    'Health Services Delivery Systems': 'RAND Health',
    'Center for Military Health Policy Research': 'RAND Health',
    'Center for the Study of Employee Health Benefits': 'RAND Health',
    'Center for Domestic and International Health Security': 'RAND Health',
    'Health Sciences Program': 'RAND Health',
    'Community Health and Environmental Policy': 'RAND Health',
    'RAND/UCLA Center for Health Policy Study': 'RAND Health',
    
    # RAND Education & Labor
    'RAND Education and Labor': 'RAND Education & Labor',
    'RAND Education': 'RAND Education & Labor',
    'Rand Education': 'RAND Education & Labor',
    'Rand Education.': 'RAND Education & Labor',
    'Education and Labor': 'RAND Education & Labor',
    'Labor and Population Program': 'RAND Education & Labor',
    'Labor and Population Program.': 'RAND Education & Labor',
    'Labor and Population': 'RAND Education & Labor',
    'Labor & Population': 'RAND Education & Labor',
    'Pardee RAND Graduate School': 'RAND Education & Labor',
    'Pardee RAND': 'RAND Education & Labor',
    'Pardee Rand Graduate School': 'RAND Education & Labor',
    'Rand Graduate School': 'RAND Education & Labor',
    'RAND Graduate School': 'RAND Education & Labor',
    'RAND Graduate Institute': 'RAND Education & Labor',
    'Rand Graduate Institute': 'RAND Education & Labor',
    'Rand Institute on Education & Training': 'RAND Education & Labor',
    'Personnel Training and Health': 'RAND Education & Labor',
    'Personnel, Training, and Health': 'RAND Education & Labor',
    'Personnel, Training, and Health Program': 'RAND Education & Labor',
    'Personnel Training and Health Program': 'RAND Education & Labor',
    'Manpower Personnel and Training Program': 'RAND Education & Labor',
    'Manpower, Personnel, and Training Program': 'RAND Education & Labor',
    'Manpower, Personnel, and Training': 'RAND Education & Labor',
    'RAND Pardee Center': 'RAND Education & Labor',
    'RAND Pardee Center.': 'RAND Education & Labor',
    'PARDEE RAND': 'RAND Education & Labor',
    'RAND Frederick S. Pardee Center for Longer Range Global Policy and the Future Human Condition': 'RAND Education & Labor',
    
    # RAND Social & Economic Well-Being
    'RAND Social and Economic Well-Being': 'RAND Social & Economic Well-Being',
    'RAND Social and Economic Wellbeing': 'RAND Social & Economic Well-Being',
    'RAND Social and Economic Well-Being': 'RAND Social & Economic Well-Being',
    'Social and Economic Well-Being': 'RAND Social & Economic Well-Being',
    'Social and Economic Wellbeing': 'RAND Social & Economic Well-Being',
    'Social and Economic Well Being': 'RAND Social & Economic Well-Being',
    'Economics': 'RAND Social & Economic Well-Being',
    'Economics.': 'RAND Social & Economic Well-Being',
    'Social Sciences': 'RAND Social & Economic Well-Being',
    'Social sciences': 'RAND Social & Economic Well-Being',
    'Social Science': 'RAND Social & Economic Well-Being',
    'Social Policy': 'RAND Social & Economic Well-Being',
    'Social and Behavioral Policy': 'RAND Social & Economic Well-Being',
    'Social and Behavioral Policy': 'RAND Social & Economic Well-Being',
    
    # RAND Justice, Infrastructure & Environment
    'RAND Justice, Infrastructure, and Environment': 'RAND Justice, Infrastructure & Environment',
    'Justice, Infrastructure, and Environment': 'RAND Justice, Infrastructure & Environment',
    'Justice, Infrastructure and Environment': 'RAND Justice, Infrastructure & Environment',
    'Justice and Environment': 'RAND Justice, Infrastructure & Environment',
    'Infrastructure, Safety, and Environment': 'RAND Justice, Infrastructure & Environment',
    'infrastructure, Safety, and Environment': 'RAND Justice, Infrastructure & Environment',
    'Infrastructure, Safety and Environment': 'RAND Justice, Infrastructure & Environment',
    'Infrastructure, Safety & Environment': 'RAND Justice, Infrastructure & Environment',
    'Environmental Sciences': 'RAND Justice, Infrastructure & Environment',
    'Justice Policy': 'RAND Justice, Infrastructure & Environment',
    'Criminal Justice': 'RAND Justice, Infrastructure & Environment',
    'Criminal Justice Program': 'RAND Justice, Infrastructure & Environment',
    'Public Safety and Justice Program': 'RAND Justice, Infrastructure & Environment',
    'Public Safety and Justice': 'RAND Justice, Infrastructure & Environment',
    'Institute for Civil Justice': 'RAND Justice, Infrastructure & Environment',
    'Institute for Civil Justice (U.S.)': 'RAND Justice, Infrastructure & Environment',
    'Infrastructure Resilience and Environmental Policy': 'RAND Justice, Infrastructure & Environment',
    'Rand Infrastructure, Safety, and Environment': 'RAND Justice, Infrastructure & Environment',
    'Rand Infrastructure, Safety, and Environment (Organization)': 'RAND Justice, Infrastructure & Environment',
    'RAND Law, Business, and Regulation': 'RAND Justice, Infrastructure & Environment',
    'RAND Law, Business, and Regulation.': 'RAND Justice, Infrastructure & Environment',
    'Law, Business, and Regulation': 'RAND Justice, Infrastructure & Environment',
    'Rand Justice, Infrastructure, and Environment': 'RAND Justice, Infrastructure & Environment',
    'RAND, Justice, Infrastructure, and Environment': 'RAND Justice, Infrastructure & Environment',
    
    # RAND National Security Research Division
    'RAND National Security Research Division': 'RAND National Security Research Division',
    'National Security Research Division': 'RAND National Security Research Division',
    'National Security Research Division.': 'RAND National Security Research Division',
    'National Security Research': 'RAND National Security Research Division',
    'National Security Research Diviision': 'RAND National Security Research Division',
    'International Security and Defense Policy Center': 'RAND National Security Research Division',
    'International Security and Defense Policy': 'RAND National Security Research Division',
    'International Security and Defense Strategy': 'RAND National Security Research Division',
    'international security and defense strategy': 'RAND National Security Research Division',
    'Defense Planning and Analysis': 'RAND National Security Research Division',
    'Defense and Technology Planning': 'RAND National Security Research Division',
    'Defense Policy Analysis': 'RAND National Security Research Division',
    'Defense Policy and Analysis': 'RAND National Security Research Division',
    'Forces and Resources Policy Center': 'RAND National Security Research Division',
    'Acquisition and Technology Policy Center': 'RAND National Security Research Division',
    'Acquisition and Development Program': 'RAND National Security Research Division',
    'Acquisitions and Development Program': 'RAND National Security Research Division',
    'Acquisition and Support Policy': 'RAND National Security Research Division',
    'Acquisition': 'RAND National Security Research Division',
    'Defense Manpower Research Center': 'RAND National Security Research Division',
    'Defense Manpower Research': 'RAND National Security Research Division',
    'Defense Advisory Group': 'RAND National Security Research Division',
    'Defense Technologies and Planning': 'RAND National Security Research Division',
    'Defense Technology and Planning': 'RAND National Security Research Division',
    'Strategic Communications': 'RAND National Security Research Division',
    'National Security Strategies': 'RAND National Security Research Division',
    'National Security Strategies Program': 'RAND National Security Research Division',
    'National Security Study Directive (NSSD)': 'RAND National Security Research Division',
    'National Security Defense Division': 'RAND National Security Research Division',
    'National Security Research Institute': 'RAND National Security Research Division',
    'RAND National Security Research Institute': 'RAND National Security Research Division',
    'RAND Security Defense Research Division': 'RAND National Security Research Division',
    'Nattional Defense Research Institute': 'RAND National Security Research Division',
    
    # RAND Europe (International)
    'RAND Europe': 'RAND Europe',
    'Rand Europe': 'RAND Europe',
    'RAND Europe.': 'RAND Europe',
    'RAND Australia': 'RAND Europe',
    'RAND International': 'RAND Europe',
    'RAND International Programs': 'RAND Europe',
    'International Programs': 'RAND Europe',
    'International': 'RAND Europe',
    'International Policy': 'RAND Europe',
    'International Economic Policy': 'RAND Europe',
    'New York City RAND Institute': 'RAND Europe',
    'Rand-Qatar Policy Institute': 'RAND Europe',
    'RAND-Qatar Policy Institute': 'RAND Europe',
    'RAND Gulf States Policy Institute': 'RAND Europe',
    'Gulf States Policy Institute': 'RAND Europe',
    'Rand Gulf States Policy Institute': 'RAND Europe',
    'Center for Asia-Pacific Policy': 'RAND Europe',
    'Center for Asia Pacific Policy': 'RAND Europe',
    'RAND Center for Asia Pacific Policy': 'RAND Europe',
    'Center for Russian and Eurasian Studies': 'RAND Europe',
    'Center for Russia and Eurasia': 'RAND Europe',
    'Center for Global Risk and Security': 'RAND Europe',
    'Center for Middle East Public Policy': 'RAND Europe',
    'Center for Middle East Policy': 'RAND Europe',
    'Center for Terrorism Risk Management Policy': 'RAND Europe',
    'RAND Center for Terrorism Risk Management Policy': 'RAND Europe',
    'RAND Global and Emerging Risks': 'RAND Europe',
    'RAND Global & Emerging Risks': 'RAND Europe',
    'European-American Center for Policy Analysis': 'RAND Europe',
    
    # Corporate & Administration
    'RAND Corporation': 'Corporate & Administration',
    'Rand Corporation': 'Corporate & Administration',
    'Rand Corporation.': 'Corporate & Administration',
    'Rand Corporaton': 'Corporate & Administration',
    'Rand Corportaion': 'Corporate & Administration',
    'Rand corporation': 'Corporate & Administration',
    'RAND': 'Corporate & Administration',
    'Administration': 'Corporate & Administration',
    'Administration.': 'Corporate & Administration',
    'Office of External Affairs': 'Corporate & Administration',
    'RAND Office of External Affairs': 'Corporate & Administration',
    'RAND Office of External Affairs.': 'Corporate & Administration',
    'Office of Services': 'Corporate & Administration',
    'Office of Congressional Relations': 'Corporate & Administration',
    'Office of The President': 'Corporate & Administration',
    'President Office': 'Corporate & Administration',
    'President Office': 'Corporate & Administration',
    'VPFA': 'Corporate & Administration',
    'Mail and Records': 'Corporate & Administration',
    'Research Staff Management Department': 'Corporate & Administration',
    'RAND Institutional': 'Corporate & Administration',
    'RAND Institutional - General': 'Corporate & Administration',
    'RAND Corporate': 'Corporate & Administration',
    'RAND Internal Research and Development': 'Corporate & Administration',
    'RAND-Sponsored Research': 'Corporate & Administration',
    'RAND Enterprise Analysis': 'Corporate & Administration',
    'Research Council': 'Corporate & Administration',
    'Research Programming': 'Corporate & Administration',
    'Publications': 'Corporate & Administration',
    'Reports': 'Corporate & Administration',
    'Library': 'Corporate & Administration',
    'Sub-Contractor': 'Corporate & Administration',
    'Sub-Contractors': 'Corporate & Administration',
    'Project Rand (United States. Air Force)': 'Corporate & Administration',
    'PRO': 'Corporate & Administration',
    'Project RAND': 'Corporate & Administration',
    'Rad': 'Corporate & Administration',
    'RD': 'Corporate & Administration',
    'NA': 'Corporate & Administration',
    'FISC': 'Corporate & Administration',
    'ISA': 'Corporate & Administration',
    'FO': 'Corporate & Administration',
    'CCOM': 'Corporate & Administration',
    'SD': 'Corporate & Administration',
    'STP': 'Corporate & Administration',
    'C3I': 'Corporate & Administration',
    'MIS': 'Corporate & Administration',
    'LSL': 'Corporate & Administration',
    'TechCo': 'Corporate & Administration',
    'TIS Staff': 'Corporate & Administration',
    'SRL Staff and Systems Training Project Staff': 'Corporate & Administration',
    
    # Engineering & Technology
    'Engineering': 'Engineering & Technology',
    'Engineering Sciences': 'Engineering & Technology',
    'Engineering and Applied Sciences': 'Engineering & Technology',
    'Engineering Analysis': 'Engineering & Technology',
    'Engineering and Social Science': 'Engineering & Technology',
    'Computer Sciences': 'Engineering & Technology',
    'Computer Science': 'Engineering & Technology',
    'Computer sciences': 'Engineering & Technology',
    'computer science': 'Engineering & Technology',
    'Computer Science-Mathematics': 'Engineering & Technology',
    'Computer Information Systems': 'Engineering & Technology',
    'Computer Analysis': 'Engineering & Technology',
    'Information Sciences': 'Engineering & Technology',
    'Information Science Methodologies': 'Engineering & Technology',
    'Information Processing Systems': 'Engineering & Technology',
    'Business Information Systems': 'Engineering & Technology',
    'Center for Information-Revolution Analysis': 'Engineering & Technology',
    'Mathematics': 'Engineering & Technology',
    'Mathematics-Red Wood': 'Engineering & Technology',
    'Mathematic sematics': 'Engineering & Technology',
    'Numerical Analysis': 'Engineering & Technology',
    'Numerican Analysis': 'Engineering & Technology',
    'Physics': 'Engineering & Technology',
    'Physical Sciences': 'Engineering & Technology',
    'Nuclear Sciences': 'Engineering & Technology',
    'Nuclear Energy': 'Engineering & Technology',
    'Electronics': 'Engineering & Technology',
    'Electronic': 'Engineering & Technology',
    'Geophysics and Astronomy': 'Engineering & Technology',
    'Planetary Sciences': 'Engineering & Technology',
    'Planetary Science': 'Engineering & Technology',
    'Systems Sciences': 'Engineering & Technology',
    'Systems Operations': 'Engineering & Technology',
    'Systems operations': 'Engineering & Technology',
    'Systems Operations - Red Wood': 'Engineering & Technology',
    'Mathematics and Systems Operations': 'Engineering & Technology',
    'Management Sciences Engineering Sciences': 'Engineering & Technology',
    'Systems Development Division': 'Engineering & Technology',
    'Systems Development Division.': 'Engineering & Technology',
    'Science and Technology Policy Institute': 'Engineering & Technology',
    'Science and technology Division': 'Engineering & Technology',
    'RAND Science and Technology': 'Engineering & Technology',
    'Applied Science and Technology': 'Engineering & Technology',
    'Applied Sciences': 'Engineering & Technology',
    'Critical Technologies Institute': 'Engineering & Technology',
    'Aerospace and Strategic Technology': 'Engineering & Technology',
    'Mechanical Sciences': 'Engineering & Technology',
    'Plant Science': 'Engineering & Technology',
    'Respiration': 'Engineering & Technology',
    'Cognitive Science': 'Engineering & Technology',
    'Linguistics': 'Engineering & Technology',
    'Business management': 'Engineering & Technology',
    'Managements Sciences': 'Engineering & Technology',
    'Management Sciences': 'Engineering & Technology',
    'Cost Analysis': 'Engineering & Technology',
    'Cost analysis': 'Engineering & Technology',
    'COST ANALYSIS': 'Engineering & Technology',
    'Logistics': 'Engineering & Technology',
    'Logistics.': 'Engineering & Technology',
    'Losgistics': 'Engineering & Technology',
    'Logistic': 'Engineering & Technology',
    'Logistics Systems Laboratory': 'Engineering & Technology',
    'Forces and Logistics': 'Engineering & Technology',
    'Forces and Logistics Program': 'Engineering & Technology',
    'Resource Analysis': 'Engineering & Technology',
    'Resource analysis': 'Engineering & Technology',
    'Resource Management': 'Engineering & Technology',
    'Resource Management Program': 'Engineering & Technology',
    'Resource Management and System Acquisition': 'Engineering & Technology',
    'Resource Management and System Acquisition.': 'Engineering & Technology',
    'Resource Management, Human Capital': 'Engineering & Technology',
    'Human Capital': 'Engineering & Technology',
    'Human and Material Resource Policy': 'Engineering & Technology',
    'Human and Material Resources Policy': 'Engineering & Technology',
    'Human and Material Research Policy': 'Engineering & Technology',
    'Personnel': 'Engineering & Technology',
    'Investment in People and Ideas': 'Engineering & Technology',
    'Behavioral Sciences': 'Engineering & Technology',
    'Political Science': 'Engineering & Technology',
    'Political Science.': 'Engineering & Technology',
    'Political science': 'Engineering & Technology',
    'Tactical Operations': 'Engineering & Technology',
    'Force Modernization and Employment Program': 'Engineering & Technology',
    'Force Employment Program': 'Engineering & Technology',
    'Force Structure and Modernization': 'Engineering & Technology',
    'Strategy and Resources Program': 'Engineering & Technology',
    'Strategy and Doctrine Program': 'Engineering & Technology',
    'Strategy and Doctrine (Air Force)': 'Engineering & Technology',
    'Strategy Policy and Operations Program': 'Engineering & Technology',
    'Strategy Policy  and Operations Program': 'Engineering & Technology',
    'Strategy, Policy, and Operations Program': 'Engineering & Technology',
    'Strategy, Doctrine, and Resources Program': 'Engineering & Technology',
    'Plans Analysis': 'Engineering & Technology',
    'Preliminary Design Section': 'Engineering & Technology',
    'Military Operations Simulation Facility': 'Engineering & Technology',
    'Domestic Research': 'Engineering & Technology',
    'Domestic research': 'Engineering & Technology',
    'Domestic Programs Division': 'Engineering & Technology',
    'Domestic Programs': 'Engineering & Technology',
    'Drug Policy Research Center': 'Engineering & Technology',
    'RAND Drug Policy Research Center': 'Engineering & Technology',
    'Emerging Policy Research and Methods': 'Engineering & Technology',
    'Science, Technology, and Policy Program': 'Engineering & Technology',
    'Communications': 'Engineering & Technology',
    'Intelligence Policy Center': 'Engineering & Technology',
    'Cyber and Intelligence Policy Center': 'Engineering & Technology',
    'Survey Research Group': 'Engineering & Technology',
}

def get_research_area_mapping():
    """Get the research area mapping dictionary."""
    return RESEARCH_AREA_MAPPING

def get_research_areas():
    """Get list of unique research areas."""
    return sorted(set(RESEARCH_AREA_MAPPING.values()))

def categorize_local_data(local_data_value):
    """Categorize a local_data value into a research area."""
    return RESEARCH_AREA_MAPPING.get(local_data_value, 'Uncategorized')

if __name__ == "__main__":
    print('Research Area Mapping Analysis')
    print(f'Total mappings: {len(RESEARCH_AREA_MAPPING)}')
    print()
    print('Categories:')
    categories = get_research_areas()
    for i, cat in enumerate(categories, 1):
        count = sum(1 for v in RESEARCH_AREA_MAPPING.values() if v == cat)
        print(f'{i:2d}. {cat} ({count} divisions)')


