#!/usr/bin/env python3
"""
Deep test: Check if the SQL query is correct when symbolization is used
"""

import sys
import os
import json

# Add parent directory to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from psycopg2.pool import SimpleConnectionPool
from psycopg2.extras import DictCursor
import requests

API_BASE_URL = "http://localhost:5001/api"

def test_query_generation():
    """Test the actual SQL query generated by the API"""
    print("\n" + "="*60)
    print("TEST: Check SQL Query Generated by API")
    print("="*60)
    
    url = f"{API_BASE_URL}/papers"
    params = {
        'limit': 5,
        'symbolization_id': 4,
        'fields': 'doctrove_paper_id,doctrove_title'
    }
    
    print(f"Request: {params}")
    
    try:
        response = requests.get(url, params=params, timeout=10)
        if response.status_code == 200:
            data = response.json()
            
            # Check if query is in response
            query = data.get('query', '')
            print(f"\n✅ Generated SQL Query:")
            print(query)
            
            # Check if country_uschina is in the SELECT
            if 'country_uschina' in query.upper() or 'ec.country_uschina' in query:
                print("\n✅ country_uschina IS in the SELECT clause")
            else:
                print("\n❌ country_uschina NOT in the SELECT clause")
            
            # Check results
            results = data.get('results', [])
            print(f"\n✅ Returned {len(results)} papers")
            
            # Count papers with non-null values
            with_values = [r for r in results if r.get('country_uschina') is not None]
            without_values = [r for r in results if r.get('country_uschina') is None]
            
            print(f"   Papers WITH country_uschina values: {len(with_values)}")
            print(f"   Papers WITHOUT country_uschina values: {len(without_values)}")
            
            if with_values:
                print(f"\n   Sample papers WITH values:")
                for i, paper in enumerate(with_values[:3]):
                    print(f"      {i+1}. {paper.get('country_uschina')}")
            
            if without_values:
                print(f"\n   Sample papers WITHOUT values (first 3):")
                for i, paper in enumerate(without_values[:3]):
                    print(f"      {i+1}. Paper ID: {paper.get('doctrove_paper_id')[:8]}...")
            
            # Check what fields are actually returned
            if results:
                print(f"\n   Fields in response: {list(results[0].keys())}")
                
    except Exception as e:
        print(f"❌ Error: {e}")
        import traceback
        traceback.print_exc()

def test_with_explicit_filter():
    """Test with filter to get papers that definitely have data"""
    print("\n" + "="*60)
    print("TEST: Query with filter for papers WITH enrichment data")
    print("="*60)
    
    url = f"{API_BASE_URL}/papers"
    params = {
        'limit': 20,
        'symbolization_id': 4,
        'fields': 'doctrove_paper_id,doctrove_title',
        'sql_filter': 'enrichment_country.country_uschina IS NOT NULL'
    }
    
    print(f"Request: {params}")
    
    try:
        response = requests.get(url, params=params, timeout=10)
        if response.status_code == 200:
            data = response.json()
            results = data.get('results', [])
            
            print(f"\n✅ Returned {len(results)} papers")
            
            if results:
                # Count unique values
                value_counts = {}
                for paper in results:
                    val = paper.get('country_uschina')
                    value_counts[val] = value_counts.get(val, 0) + 1
                
                print(f"\n   Value distribution:")
                for val, count in sorted(value_counts.items(), key=lambda x: -x[1]):
                    print(f"      {val}: {count} papers")
                
                # Sample papers
                print(f"\n   Sample papers:")
                for i, paper in enumerate(results[:5]):
                    print(f"      {i+1}. {paper.get('doctrove_title')[:50]}...")
                    print(f"         country_uschina: {paper.get('country_uschina')}")
                    
    except Exception as e:
        print(f"❌ Error: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    test_query_generation()
    test_with_explicit_filter()

